# Leitura dos dados - Camada Gold
Exploracao das tabelas analiticas geradas na camada Gold.

In [1]:
from pathlib import Path
import pandas as pd

GOLD_DIR = Path("../data/gold")

## Fato Vendas

In [2]:
fato = pd.read_parquet(GOLD_DIR / "fato_vendas.parquet")

print("Shape:", fato.shape)
print("\nColunas:", list(fato.columns))
fato.head()

Shape: (56046, 16)

Colunas: ['Data da Venda', 'Ordem de Compra', 'SKU', 'ID Cliente', 'Qtd Vendida', 'ID Loja', 'Produto', 'Marca', 'Tipo do Produto', 'Preço Unitario', 'Custo Unitario', 'valor_total', 'custo_total', 'lucro', 'data_ingestao', 'origem']

,Data da Venda,Ordem de Compra,SKU,ID Cliente,Qtd Vendida,ID Loja,Produto,Marca,Tipo do Produto,Preço Unitario,Custo Unitario,valor_total,custo_total,lucro,data_ingestao,origem
0,2020-01-01 00:00:00,SO45080,HL59,14657,1,101,iPhone SE 256GB - Preto,Apple,Celular,579.0,115.8,579.0,115.8,463.2,2026-06-08 22:57:38,silver/vendas.parquet + silver/produtos.parquet
1,2020-01-01 00:00:00,SO45079,HL45,29255,1,122,iPhone 13 Pro Max 512GB - Vermelho,Apple,Celular,1399.0,377.7,1399.0,377.7,1021.3,2026-06-08 22:57:38,silver/vendas.parquet + silver/produtos.parquet
2,2020-01-01 00:00:00,SO45082,HL71,11455,1,200,iPhone 12 Mini 128GB - Preto,Apple,Celular,549.0,115.3,549.0,115.3,433.7,2026-06-08 22:57:38,silver/vendas.parquet + silver/produtos.parquet
3,2020-01-01 00:00:00,SO45081,HL62,26782,1,200,iPhone 12 Pro Max 512GB - Preto,Apple,Celular,1249.0,362.2,1249.0,362.2,886.8,2026-06-08 22:57:38,silver/vendas.parquet + silver/produtos.parquet
4,2020-01-02 00:00:00,SO45083,HL45,14947,1,199,iPhone 13 Pro Max 512GB - Vermelho,Apple,Celular,1399.0,377.7,1399.0,377.7,1021.3,2026-06-08 22:57:38,silver/vendas.parquet + silver/produtos.parquet

In [3]:
print("Totais gerais:")
print("Valor total vendido: R$", round(float(fato["valor_total"].sum()), 2))
print("Custo total:         R$", round(float(fato["custo_total"].sum()), 2))
print("Lucro total:         R$", round(float(fato["lucro"].sum()), 2))

Totais gerais:
Valor total vendido: R$ 15226080.56
Custo total:         R$ 3860844.9
Lucro total:         R$ 11365235.66

## Vendas por Periodo

In [4]:
periodo = pd.read_parquet(GOLD_DIR / "vendas_por_periodo.parquet")

print("Shape:", periodo.shape)
periodo

Shape: (30, 9)

,ano,mes,qtd_vendida,valor_total,custo_total,lucro,num_pedidos,data_ingestao,origem
0,2020,1,184,206816.0,54025.3,152790.7,184,2026-06-08 22:57:38,gold/fato_vendas.parquet
1,2020,2,165,198015.0,51076.6,146938.4,165,2026-06-08 22:57:38,gold/fato_vendas.parquet
2,2020,3,198,227242.0,58239.2,169002.8,198,2026-06-08 22:57:38,gold/fato_vendas.parquet
3,2020,4,204,234126.0,60715.1,173410.9,204,2026-06-08 22:57:38,gold/fato_vendas.parquet
4,2020,5,206,233014.0,59789.0,173225.0,206,2026-06-08 22:57:38,gold/fato_vendas.parquet
5,2020,6,212,240478.0,61793.6,178684.4,212,2026-06-08 22:57:38,gold/fato_vendas.parquet
6,2020,7,247,125730.03,30278.5,95451.53,247,2026-06-08 22:57:38,gold/fato_vendas.parquet
7,2020,8,278,150265.26,36093.3,114171.96,278,2026-06-08 22:57:38,gold/fato_vendas.parquet
8,2020,9,196,112228.91,27677.4,84551.51,196,2026-06-08 22:57:38,gold/fato_vendas.parquet
9,2020,10,223,131318.6,31698.2,99620.4,223,2026-06-08 22:57:38,gold/fato_vendas.parquet
10,2020,11,191,114326.09,28283.3,86042.79,191,2026-06-08 22:57:38,gold/fato_vendas.parquet
11,2020,12,326,210200.52,51078.6,159121.92,326,2026-06-08 22:57:38,gold/fato_vendas.parquet
12,2021,1,242,142520.08,34010.8,108509.28,242,2026-06-08 22:57:38,gold/fato_vendas.parquet
13,2021,2,267,158823.3,38242.0,120581.3,267,2026-06-08 22:57:38,gold/fato_vendas.parquet
14,2021,3,266,161595.85,39454.9,122140.95,266,2026-06-08 22:57:38,gold/fato_vendas.parquet
15,2021,4,290,186502.86,45411.8,141091.06,290,2026-06-08 22:57:38,gold/fato_vendas.parquet
16,2021,5,329,210909.37,51024.7,159884.67,329,2026-06-08 22:57:38,gold/fato_vendas.parquet
17,2021,6,312,201593.83,48781.7,152812.13,312,2026-06-08 22:57:38,gold/fato_vendas.parquet
18,2021,7,1954,484413.87,118118.5,366295.37,506,2026-06-08 22:57:38,gold/fato_vendas.parquet
19,2021,8,5958,667396.28,173644.1,493752.18,1543,2026-06-08 22:57:38,gold/fato_vendas.parquet
20,2021,9,5970,769138.4,197579.6,571558.8,1568,2026-06-08 22:57:38,gold/fato_vendas.parquet
21,2021,10,6387,826246.46,212572.0,613674.46,1639,2026-06-08 22:57:38,gold/fato_vendas.parquet
22,2021,11,6332,892223.04,227702.3,664520.74,1677,2026-06-08 22:57:38,gold/fato_vendas.parquet
23,2021,12,7923,1281497.34,325664.5,955832.84,2056,2026-06-08 22:57:38,gold/fato_vendas.parquet
24,2022,1,7020,994701.35,256926.6,737774.75,1811,2026-06-08 22:57:38,gold/fato_vendas.parquet
25,2022,2,6828,984548.49,251559.2,732989.29,1758,2026-06-08 22:57:38,gold/fato_vendas.parquet
26,2022,3,7327,1097108.55,279937.1,817171.45,1962,2026-06-08 22:57:38,gold/fato_vendas.parquet
27,2022,4,7680,1178353.31,299360.0,878993.31,1997,2026-06-08 22:57:38,gold/fato_vendas.parquet
28,2022,5,8199,1388069.88,352311.4,1035758.48,2165,2026-06-08 22:57:38,gold/fato_vendas.parquet
29,2022,6,8260,1416677.89,357795.6,1058882.29,2146,2026-06-08 22:57:38,gold/fato_vendas.parquet

In [5]:
print("Melhor mes (lucro):")
print(periodo.loc[periodo["lucro"].idxmax()].to_string())

Melhor mes (lucro):
ano                                  2022
mes                                     6
qtd_vendida                          8260
valor_total                    1416677.89
custo_total                      357795.6
lucro                          1058882.29
num_pedidos                          2146
data_ingestao         2026-06-08 22:57:38
origem           gold/fato_vendas.parquet

## Vendas por Loja

In [6]:
lojas = pd.read_parquet(GOLD_DIR / "vendas_por_loja.parquet")

print("Shape:", lojas.shape)
lojas.head(10)

Shape: (293, 12)

,ID Loja,Nome da Loja,Tipo,País,Continente,qtd_vendida,valor_total,custo_total,lucro,num_pedidos,data_ingestao,origem
0,200,Loja Catalog,Física,Estados Unidos,América do Norte,5213,1053605.04,265134.1,788470.94,1939,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
1,199,Loja North America Online,Online,Estados Unidos,América do Norte,4927,854544.57,218373.4,636171.17,1866,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
2,306,Loja Europe Online,Online,Alemanha,Europa,4799,827454.52,212372.7,615081.82,1843,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
3,307,Loja Asia Online,Online,China,Ásia,4562,817054.34,209713.8,607340.54,1736,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
4,308,Loja North America Reseller,Física,Estados Unidos,América do Norte,3802,677311.44,173814.6,503496.84,1472,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
5,309,Loja Europe Reseller,Física,França,Europa,3641,652580.69,164660.7,487919.99,1431,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
6,310,Loja Asia Reseller,Física,China,Ásia,3264,563263.79,144246.3,419017.49,1275,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
7,254,Loja Yerevan,Física,Armênia,Ásia,275,75492.25,19196.8,56295.45,180,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
8,281,Loja Shanghai No.2,Física,China,Ásia,313,74992.45,18199.1,56793.35,199,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...
9,267,Loja Tokyo No.1,Física,Japão,Ásia,320,73815.17,18396.0,55419.17,205,2026-06-08 22:57:38,gold/fato_vendas.parquet + silver/lojas.parque...

In [7]:
print("Vendas por continente:")
lojas.groupby("Continente")[["valor_total", "lucro"]].sum().sort_values("lucro", ascending=False)

Vendas por continente:

                  valor_total       lucro
Continente
América do Norte   9297987.22  6943287.72
Ásia               2928697.88  2184289.08
Europa             2838032.47  2116553.57
Oceania             161362.99   121105.29

In [8]:
print("Vendas por tipo de loja:")
lojas.groupby("Tipo")[["valor_total", "lucro", "qtd_vendida"]].sum().sort_values("lucro", ascending=False)

Vendas por tipo de loja:

        valor_total       lucro  qtd_vendida
Tipo
Física  12727027.13  9506642.13        69886
Online   2499053.43  1858593.53        14288

## Devolucoes por Motivo

In [9]:
devolucoes = pd.read_parquet(GOLD_DIR / "devolucoes_por_motivo.parquet")

print("Shape:", devolucoes.shape)
devolucoes

Shape: (65, 7)

,Motivo Devolução,Tipo do Produto,Marca,qtd_devolvida,num_ocorrencias,data_ingestao,origem
0,Produto com defeito,Mouse,Multilaser,274,265,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
1,Produto com defeito,Mouse,Logitech,246,243,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
2,Produto com defeito,Teclado,LG,157,154,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
3,Produto com defeito,Celular,Apple,146,145,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
4,Produto com defeito,Casaco,Hashtag,127,127,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
...,...,...,...,...,...,...,...
60,Não informado,Notebook,Asus,1,1,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
61,Não informado,Notebook,HP,1,1,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
62,Não informado,Notebook,LG,1,1,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
63,Não informado,Notebook,Samsung,1,1,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...
64,Não informado,Notebook,Vaio,1,1,2026-06-08 22:57:38,silver/devolucoes.parquet + silver/produtos.pa...

In [10]:
print("Devolucoes por motivo (total):")
devolucoes.groupby("Motivo Devolução")[["qtd_devolvida", "num_ocorrencias"]].sum().sort_values("qtd_devolvida", ascending=False)

Devolucoes por motivo (total):

                     qtd_devolvida  num_ocorrencias
Motivo Devolução
Produto com defeito           1618             1600
Arrependimento                 105              104
Troca Indisponível              54               54
Não informado                   51               51