# Leitura dos dados - Camada Silver
Exploracao dos arquivos Parquet gerados na camada Silver.

In [ ]:
from pathlib import Path
import pandas as pd

SILVER_DIR = Path("../data/silver")

## Vendas (consolidado 2020-2022)

In [ ]:
vendas = pd.read_parquet(SILVER_DIR / "vendas.parquet")

print("Shape:", vendas.shape)
print("\nDtypes:")
print(vendas.dtypes)
vendas.head()

Shape: (56046, 8)

Dtypes:
Data da Venda      timestamp[us][pyarrow]
Ordem de Compra                    string
SKU                                string
ID Cliente                 int64[pyarrow]
Qtd Vendida                int64[pyarrow]
ID Loja                    int64[pyarrow]
data_ingestao                         str
origem                                str
dtype: object

,Data da Venda,Ordem de Compra,SKU,ID Cliente,Qtd Vendida,ID Loja,data_ingestao,origem
0,2020-01-01 00:00:00,SO45080,HL59,14657,1,101,2026-06-08 22:44:56,bronze/Base Vendas - 2020|2021|2022.parquet
1,2020-01-01 00:00:00,SO45079,HL45,29255,1,122,2026-06-08 22:44:56,bronze/Base Vendas - 2020|2021|2022.parquet
2,2020-01-01 00:00:00,SO45082,HL71,11455,1,200,2026-06-08 22:44:56,bronze/Base Vendas - 2020|2021|2022.parquet
3,2020-01-01 00:00:00,SO45081,HL62,26782,1,200,2026-06-08 22:44:56,bronze/Base Vendas - 2020|2021|2022.parquet
4,2020-01-02 00:00:00,SO45083,HL45,14947,1,199,2026-06-08 22:44:56,bronze/Base Vendas - 2020|2021|2022.parquet

In [ ]:
vendas.describe()

                    Data da Venda    ID Cliente  Qtd Vendida     ID Loja
count                       56046       56046.0      56046.0     56046.0
mean   2021-12-16 19:51:03.526389  18843.645559     1.501873  197.577954
min           2020-01-01 00:00:00       11000.0          1.0         1.0
25%           2021-10-06 00:00:00       14016.0          1.0       121.0
50%           2022-01-11 00:00:00       18157.0          1.0       200.0
75%           2022-04-12 00:00:00      23425.75          2.0       301.0
max           2022-06-30 00:00:00       29483.0          3.0       310.0
std                           NaN   5412.449843     0.612379   96.444224

In [ ]:
print("Nulos por coluna:")
vendas.isnull().sum()

Nulos por coluna:

Data da Venda      0
Ordem de Compra    0
SKU                0
ID Cliente         0
Qtd Vendida        0
ID Loja            0
data_ingestao      0
origem             0
dtype: int64

In [ ]:
print("Periodo das vendas:")
print("De:", vendas["Data da Venda"].min())
print("Ate:", vendas["Data da Venda"].max())

Periodo das vendas:
De: 2020-01-01 00:00:00
Ate: 2022-06-30 00:00:00

## Devolucoes

In [ ]:
devolucoes = pd.read_parquet(SILVER_DIR / "devolucoes.parquet")

print("Shape:", devolucoes.shape)
print("\nDtypes:")
print(devolucoes.dtypes)
devolucoes.head()

Shape: (1809, 7)

Dtypes:
Data Devolução      timestamp[us][pyarrow]
ID Loja                     int64[pyarrow]
SKU                                 string
Qtd Devolvida               int64[pyarrow]
Motivo Devolução                    string
data_ingestao                          str
origem                                 str
dtype: object

,Data Devolução,ID Loja,SKU,Qtd Devolvida,Motivo Devolução,data_ingestao,origem
0,2020-01-18 00:00:00,309,HL45,1,Produto com defeito,2026-06-08 22:44:56,bronze/Base Devoluções.parquet
1,2020-01-18 00:00:00,306,HL43,1,Produto com defeito,2026-06-08 22:44:56,bronze/Base Devoluções.parquet
2,2020-01-21 00:00:00,41,HL67,1,Produto com defeito,2026-06-08 22:44:56,bronze/Base Devoluções.parquet
3,2020-01-22 00:00:00,306,HL44,1,Não informado,2026-06-08 22:44:56,bronze/Base Devoluções.parquet
4,2020-02-02 00:00:00,309,HL45,1,Produto com defeito,2026-06-08 22:44:56,bronze/Base Devoluções.parquet

In [ ]:
print("Motivos de devolucao:")
devolucoes["Motivo Devolução"].value_counts()

Motivos de devolucao:

Motivo Devolução
Produto com defeito    1600
Arrependimento          104
Troca Indisponível       54
Não informado            51
Name: count, dtype: int64[pyarrow]

## Cadastro de Clientes

In [ ]:
clientes = pd.read_parquet(SILVER_DIR / "clientes.parquet")

print("Shape:", clientes.shape)
print("\nDtypes:")
print(clientes.dtypes)
clientes.head()

Shape: (18148, 12)

Dtypes:
ID Cliente                 string
Primeiro Nome              string
Sobrenome                  string
Email                      string
Genero                     string
Data Nascimento    datetime64[us]
Estado Civil               string
Num Filhos                 string
Nivel Escolar              string
Documento                     str
data_ingestao                 str
origem                        str
dtype: object

,ID Cliente,Primeiro Nome,Sobrenome,Email,Genero,Data Nascimento,Estado Civil,Num Filhos,Nivel Escolar,Documento,data_ingestao,origem
0,11000,STHEFESON,PEREIRA,sthefeson8@icloud.com,M,1966-04-08,C,2,Superior Completo,80912350,2026-06-08 22:44:56,bronze/Cadastro Clientes.parquet
1,11001,ANTONIO,MANHÃES,antonio19@hotmail.com.br,M,1965-05-14,S,3,Superior Completo,18106981686,2026-06-08 22:44:56,bronze/Cadastro Clientes.parquet
2,11002,BIANCA,PAZ,bianca53@live.com.br,F,1965-08-12,C,3,Superior Completo,77468986692,2026-06-08 22:44:56,bronze/Cadastro Clientes.parquet
3,11003,SILVIO,FAHRNHOLZ,silvio21@hotmail.com.br,M,1968-02-15,S,0,Superior Completo,28009530521,2026-06-08 22:44:56,bronze/Cadastro Clientes.parquet
4,11004,LUIZA,CABRAL,luiza70@msn.com,F,1968-08-08,S,5,Superior Completo,16316472002,2026-06-08 22:44:56,bronze/Cadastro Clientes.parquet

In [ ]:
print("Genero:")
print(clientes["Genero"].value_counts())
print("\nEstado Civil:")
print(clientes["Estado Civil"].value_counts())
print("\nNivel Escolar:")
print(clientes["Nivel Escolar"].value_counts())

Genero:
Genero
M    9137
F    9011
Name: count, dtype: int64[pyarrow]

Estado Civil:
Estado Civil
C    9817
S    8331
Name: count, dtype: int64[pyarrow]

Nivel Escolar:
Nivel Escolar
Superior Completo          5261
Superior Incompleto        4966
Ensino Médio Completo      3241
Pós Graduação              3125
Ensino Médio Incompleto    1555
Name: count, dtype: int64[pyarrow]

## Cadastro de Produtos

In [ ]:
produtos = pd.read_parquet(SILVER_DIR / "produtos.parquet")

print("Shape:", produtos.shape)
print("\nDtypes:")
print(produtos.dtypes)
produtos.head()

Shape: (293, 8)

Dtypes:
SKU                         string
Produto                     string
Marca                       string
Tipo do Produto             string
Preço Unitario     double[pyarrow]
Custo Unitario     double[pyarrow]
data_ingestao                  str
origem                         str
dtype: object

,SKU,Produto,Marca,Tipo do Produto,Preço Unitario,Custo Unitario,data_ingestao,origem
0,HL1,M510 Mouse sem fio - Vermelho,Logitech,Mouse,25.95,6.5,2026-06-08 22:44:56,bronze/Cadastro Produtos.parquet
1,HL2,Mouse sem fio M170 - Preto,Logitech,Mouse,19.95,5.0,2026-06-08 22:44:56,bronze/Cadastro Produtos.parquet
2,HL3,"Camisa Hashtag Eletro Masculina, P - Branco",Hashtag,Camisa,25.0,11.0,2026-06-08 22:44:56,bronze/Cadastro Produtos.parquet
3,HL4,"Camisa Hashtag Eletro Masculina, M - Branco",Hashtag,Camisa,25.0,11.0,2026-06-08 22:44:56,bronze/Cadastro Produtos.parquet
4,HL5,Mouse sem fio D09 - Azul,Multilaser,Mouse,11.99,3.4,2026-06-08 22:44:56,bronze/Cadastro Produtos.parquet

In [ ]:
print("Tipos de produto:")
print(produtos["Tipo do Produto"].value_counts())
print("\nMarcas:")
print(produtos["Marca"].value_counts())

Tipos de produto:
Tipo do Produto
Celular       75
Notebook      67
Televisão     35
Relógio       23
Casaco        18
Camisa        17
Câmera        15
Acessórios    14
Mouse         11
Teclado        9
Monitor        9
Name: count, dtype: int64[pyarrow]

Marcas:
Marca
Apple         61
Samsung       40
Hashtag       35
Xiaomi        15
Dell          14
LG            13
Motorola      12
HP            11
Lenovo        10
Sony          10
Acer           7
Logitech       6
Multilaser     6
Microsoft      5
Asus           5
Nikon          5
Garmin         4
Canon          4
Razer          4
Toshiba        3
SEMP           3
TCL            3
Spectre        3
Vizio          3
Insignia       3
AOC            2
Philco         2
Positivo       2
Compaq         1
Vaio           1
Name: count, dtype: int64[pyarrow]

## Cadastro de Lojas

In [ ]:
lojas = pd.read_parquet(SILVER_DIR / "lojas.parquet")

print("Shape:", lojas.shape)
print("\nDtypes:")
print(lojas.dtypes)
lojas.head()

Shape: (306, 9)

Dtypes:
ID Loja                     int64[pyarrow]
Nome da Loja                        string
Quantidade Colaboradores    int64[pyarrow]
Tipo                                string
ID Localidade               int64[pyarrow]
Gerente Loja                        string
Documento Gerente                      str
data_ingestao                          str
origem                                 str
dtype: object

,ID Loja,Nome da Loja,Quantidade Colaboradores,Tipo,ID Localidade,Gerente Loja,Documento Gerente,data_ingestao,origem
0,1,Loja Seattle No.1,17,Física,1,"Gonçalves, João",666418406,2026-06-08 22:44:56,bronze/Cadastro Lojas.parquet
1,2,Loja Seattle No.2,25,Física,1,"Pinheiro, Fernanda",782269727,2026-06-08 22:44:56,bronze/Cadastro Lojas.parquet
2,3,Loja Kennewick,26,Física,1,"Alves, Rodrigo",566476645,2026-06-08 22:44:56,bronze/Cadastro Lojas.parquet
3,4,Loja Bellevue,19,Física,1,"Costa, Raissa",598832615,2026-06-08 22:44:56,bronze/Cadastro Lojas.parquet
4,5,Loja Redmond,33,Física,1,"Monteiro, Felipe",200191505,2026-06-08 22:44:56,bronze/Cadastro Lojas.parquet

In [ ]:
print("Tipos de loja:")
print(lojas["Tipo"].value_counts())

Tipos de loja:
Tipo
Física    303
Online      3
Name: count, dtype: int64[pyarrow]

## Cadastro de Localidades

In [ ]:
localidades = pd.read_parquet(SILVER_DIR / "localidades.parquet")

print("Shape:", localidades.shape)
print("\nDtypes:")
print(localidades.dtypes)
localidades

Shape: (34, 5)

Dtypes:
ID Localidade    int64[pyarrow]
País                     string
Continente               string
data_ingestao               str
origem                      str
dtype: object

,ID Localidade,País,Continente,data_ingestao,origem
0,1,Estados Unidos,América do Norte,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
1,2,Canadá,América do Norte,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
2,3,Reino Unido,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
3,4,França,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
4,5,Itália,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
5,6,Alemanha,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
6,7,Holanda,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
7,8,Dinamarca,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
8,9,Suécia,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
9,10,Espanha,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
10,11,Eslovênia,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
11,12,Romênia,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
12,13,Suíça,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
13,14,Polônia,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
14,15,Malta,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
15,16,Irlanda,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
16,17,Grécia,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
17,18,Singapura,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
18,19,Austrália,Oceania,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
19,20,Armênia,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
20,21,Índia,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
21,22,Butão,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
22,23,China,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
23,24,Irã,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
24,25,Síria,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
25,26,Tailândia,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
26,27,Rússia,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
27,28,Turcomenistão,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
28,29,Paquistão,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
29,30,Japão,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
30,31,Coreia do Sul,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
31,32,Quirguistão,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
32,33,Indonésia,Ásia,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet
33,34,Portugal,Europa,2026-06-08 22:44:56,bronze/Cadastro Localidades.parquet