# Leitura dos dados - Camada Bronze
Exploracao inicial dos arquivos Parquet gerados na camada Bronze.

In [1]:
from pathlib import Path
import pandas as pd

BRONZE_DIR = Path("../data/bronze")

## Vendas

In [2]:
vendas_2020 = pd.read_parquet(BRONZE_DIR / "Base Vendas - 2020.parquet")
vendas_2021 = pd.read_parquet(BRONZE_DIR / "Base Vendas - 2021.parquet")
vendas_2022 = pd.read_parquet(BRONZE_DIR / "Base Vendas - 2022.parquet")

vendas = pd.concat([vendas_2020, vendas_2021, vendas_2022], ignore_index=True)

print("Shape:", vendas.shape)
print("\nDtypes:")
print(vendas.dtypes)
vendas.head()

Shape: (56046, 8)

Dtypes:
Data da Venda      timestamp[us][pyarrow]
Ordem de Compra                    string
SKU                                string
ID Cliente                 int64[pyarrow]
Qtd Vendida                int64[pyarrow]
ID Loja                    int64[pyarrow]
data_ingestao                         str
origem                                str
dtype: object

,Data da Venda,Ordem de Compra,SKU,ID Cliente,Qtd Vendida,ID Loja,data_ingestao,origem
0,2020-01-01 00:00:00,SO45080,HL59,14657,1,101,2026-06-08 22:25:46,Base Vendas - 2020.xlsx
1,2020-01-01 00:00:00,SO45079,HL45,29255,1,122,2026-06-08 22:25:46,Base Vendas - 2020.xlsx
2,2020-01-01 00:00:00,SO45082,HL71,11455,1,200,2026-06-08 22:25:46,Base Vendas - 2020.xlsx
3,2020-01-01 00:00:00,SO45081,HL62,26782,1,200,2026-06-08 22:25:46,Base Vendas - 2020.xlsx
4,2020-01-02 00:00:00,SO45083,HL45,14947,1,199,2026-06-08 22:25:46,Base Vendas - 2020.xlsx

In [3]:
vendas.describe()

                    Data da Venda    ID Cliente  Qtd Vendida     ID Loja
count                       56046       56046.0      56046.0     56046.0
mean   2021-12-16 19:51:03.526389  18843.645559     1.501873  197.577954
min           2020-01-01 00:00:00       11000.0          1.0         1.0
25%           2021-10-06 00:00:00       14016.0          1.0       121.0
50%           2022-01-11 00:00:00       18157.0          1.0       200.0
75%           2022-04-12 00:00:00      23425.75          2.0       301.0
max           2022-06-30 00:00:00       29483.0          3.0       310.0
std                           NaN   5412.449843     0.612379   96.444224

In [4]:
print("Nulos por coluna:")
vendas.isnull().sum()

Nulos por coluna:

Data da Venda      0
Ordem de Compra    0
SKU                0
ID Cliente         0
Qtd Vendida        0
ID Loja            0
data_ingestao      0
origem             0
dtype: int64

## Devolucoes

In [5]:
devolucoes = pd.read_parquet(BRONZE_DIR / "Base Devoluções.parquet")

print("Shape:", devolucoes.shape)
print("\nDtypes:")
print(devolucoes.dtypes)
devolucoes.head()

Shape: (1809, 7)

Dtypes:
Data Devolução      timestamp[us][pyarrow]
ID Loja                     int64[pyarrow]
SKU                                 string
Qtd Devolvida               int64[pyarrow]
Motivo Devolução                    string
data_ingestao                          str
origem                                 str
dtype: object

,Data Devolução,ID Loja,SKU,Qtd Devolvida,Motivo Devolução,data_ingestao,origem
0,2020-01-18 00:00:00,309,HL45,1,Produto com defeito,2026-06-08 22:25:46,Base Devoluções.xlsx
1,2020-01-18 00:00:00,306,HL43,1,Produto com defeito,2026-06-08 22:25:46,Base Devoluções.xlsx
2,2020-01-21 00:00:00,41,HL67,1,Produto com defeito,2026-06-08 22:25:46,Base Devoluções.xlsx
3,2020-01-22 00:00:00,306,HL44,1,Não informado,2026-06-08 22:25:46,Base Devoluções.xlsx
4,2020-02-02 00:00:00,309,HL45,1,Produto com defeito,2026-06-08 22:25:46,Base Devoluções.xlsx

In [6]:
print("Motivos de devolucao:")
devolucoes["Motivo Devolução"].value_counts()

Motivos de devolucao:

Motivo Devolução
Produto com defeito    1600
Arrependimento          104
Troca Indisponível       54
Não informado            51
Name: count, dtype: int64[pyarrow]

## Cadastro de Clientes

In [7]:
clientes = pd.read_parquet(BRONZE_DIR / "Cadastro Clientes.parquet")

print("Shape:", clientes.shape)
print("\nDtypes:")
print(clientes.dtypes)
clientes.head()

Shape: (18150, 14)

Dtypes:
Unnamed: 0       string
Unnamed: 1       string
Unnamed: 2       string
Unnamed: 3       string
Unnamed: 4       string
Unnamed: 5       string
Unnamed: 6       string
Unnamed: 7       string
Unnamed: 8       string
Unnamed: 9       string
                 string
Unnamed: 11      string
data_ingestao       str
origem              str
dtype: object

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,,Unnamed: 11,data_ingestao,origem
0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,,<NA>,2026-06-08 22:25:49,Cadastro Clientes.xlsx
1,ID Cliente,Primeiro Nome,Sobrenome,Email,Genero,Data Nascimento,Estado Civil,Num Filhos,Nivel Escolar,Documento,<NA>,<NA>,2026-06-08 22:25:49,Cadastro Clientes.xlsx
2,11000,STHEFESON,PEREIRA,sthefeson8@icloud.com,M,4/8/1966,C,2,Superior Completo,80912350,<NA>,<NA>,2026-06-08 22:25:49,Cadastro Clientes.xlsx
3,11001,ANTONIO,MANHÃES,antonio19@hotmail.com.br,M,5/14/1965,S,3,Superior Completo,18106981686,<NA>,<NA>,2026-06-08 22:25:49,Cadastro Clientes.xlsx
4,11002,BIANCA,PAZ,bianca53@live.com.br,F,8/12/1965,C,3,Superior Completo,77468986692,<NA>,<NA>,2026-06-08 22:25:49,Cadastro Clientes.xlsx

In [8]:
print("Nulos por coluna:")
clientes.isnull().sum()

Nulos por coluna:

Unnamed: 0           1
Unnamed: 1           1
Unnamed: 2           1
Unnamed: 3           1
Unnamed: 4           1
Unnamed: 5           1
Unnamed: 6           1
Unnamed: 7           1
Unnamed: 8           1
Unnamed: 9           1
                 18148
Unnamed: 11      18149
data_ingestao        0
origem               0
dtype: int64

## Cadastro de Produtos

In [9]:
produtos = pd.read_parquet(BRONZE_DIR / "Cadastro Produtos.parquet")

print("Shape:", produtos.shape)
print("\nDtypes:")
print(produtos.dtypes)
produtos.head()

Shape: (293, 9)

Dtypes:
SKU                         string
Produto                     string
Marca                       string
Tipo do Produto             string
Preço Unitario     double[pyarrow]
Custo Unitario     double[pyarrow]
Observação                  string
data_ingestao                  str
origem                         str
dtype: object

,SKU,Produto,Marca,Tipo do Produto,Preço Unitario,Custo Unitario,Observação,data_ingestao,origem
0,HL1,M510 Mouse sem fio - Vermelho,Logitech,Mouse,25.95,6.5,<NA>,2026-06-08 22:25:49,Cadastro Produtos.xlsx
1,HL2,Mouse sem fio M170 - Preto,Logitech,Mouse,19.95,5.0,<NA>,2026-06-08 22:25:49,Cadastro Produtos.xlsx
2,HL3,"Camisa Hashtag Eletro Masculina, P - Branco",Hashtag,Camisa,25.0,11.0,<NA>,2026-06-08 22:25:49,Cadastro Produtos.xlsx
3,HL4,"Camisa Hashtag Eletro Masculina, M - Branco",Hashtag,Camisa,25.0,11.0,Conferir estoque,2026-06-08 22:25:49,Cadastro Produtos.xlsx
4,HL5,Mouse sem fio D09 - Azul,Multilaser,Mouse,11.99,3.4,<NA>,2026-06-08 22:25:49,Cadastro Produtos.xlsx

In [10]:
print("Tipos de produto:")
produtos["Tipo do Produto"].value_counts()

Tipos de produto:

Tipo do Produto
Celular       75
Notebook      67
Televisão     35
Relógio       23
Casaco        18
Camisa        17
Câmera        15
Acessórios    14
Mouse         11
Teclado        9
Monitor        9
Name: count, dtype: int64[pyarrow]

## Cadastro de Lojas

In [11]:
lojas = pd.read_parquet(BRONZE_DIR / "Cadastro Lojas.parquet")

print("Shape:", lojas.shape)
print("\nDtypes:")
print(lojas.dtypes)
lojas.head()

Shape: (306, 9)

Dtypes:
ID Loja                     int64[pyarrow]
Nome da Loja                        string
Quantidade Colaboradores    int64[pyarrow]
Tipo                                string
id Localidade               int64[pyarrow]
Gerente Loja                        string
Documento Gerente           int64[pyarrow]
data_ingestao                          str
origem                                 str
dtype: object

,ID Loja,Nome da Loja,Quantidade Colaboradores,Tipo,id Localidade,Gerente Loja,Documento Gerente,data_ingestao,origem
0,1,Loja Seattle No.1,17,Física,1,"Gonçalves, João",666418406,2026-06-08 22:25:49,Cadastro Lojas.xlsx
1,2,Loja Seattle No.2,25,Física,1,"Pinheiro, Fernanda",782269727,2026-06-08 22:25:49,Cadastro Lojas.xlsx
2,3,Loja Kennewick,26,Física,1,"Alves, Rodrigo",566476645,2026-06-08 22:25:49,Cadastro Lojas.xlsx
3,4,Loja Bellevue,19,Física,1,"Costa, Raissa",598832615,2026-06-08 22:25:49,Cadastro Lojas.xlsx
4,5,Loja Redmond,33,Física,1,"Monteiro, Felipe",200191505,2026-06-08 22:25:49,Cadastro Lojas.xlsx

In [12]:
print("Tipos de loja:")
lojas["Tipo"].value_counts()

Tipos de loja:

Tipo
Física    303
Online      3
Name: count, dtype: int64[pyarrow]

## Cadastro de Localidades

In [13]:
localidades = pd.read_parquet(BRONZE_DIR / "Cadastro Localidades.parquet")

print("Shape:", localidades.shape)
print("\nDtypes:")
print(localidades.dtypes)
localidades.head(10)

Shape: (34, 5)

Dtypes:
ID Localidade    int64[pyarrow]
País                     string
Continente               string
data_ingestao               str
origem                      str
dtype: object

,ID Localidade,País,Continente,data_ingestao,origem
0,1,Estados Unidos,América do Norte,2026-06-08 22:25:49,Cadastro Localidades.xlsx
1,2,Canadá,América do Norte,2026-06-08 22:25:49,Cadastro Localidades.xlsx
2,3,Reino Unido,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
3,4,França,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
4,5,Itália,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
5,6,Alemanha,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
6,7,Holanda,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
7,8,Dinamarca,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
8,9,Suécia,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx
9,10,Espanha,Europa,2026-06-08 22:25:49,Cadastro Localidades.xlsx